### ISSUE TITLE
There should be a version mismatching problem

### ISSUE THREAD

**Issue by player1321** [hpcaitech/PaLM-colossalai#46]
Hi,

I tried to run your demo but I got some problems.
When using your default settings, i.e., colossalai 0.1.2, I got
```
Traceback (most recent call last):
File "train.py", line 18, in <module>
    from colossalai.utils import colo_set_process_memory_fraction, colo_device_memory_capacity
        ImportError: cannot import name 'colo_set_process_memory_fraction' from 'colossalai.utils' (/root/miniconda3/envs/pytorch/lib/python3.8/site-packages/colossalai/utils/__init__.py)
```
Then I tried to upgrade to colossalai 0.1.3, I got
```
Traceback (most recent call last):
File "train.py", line 176, in <module>
    train_palm()
File "train.py", line 149, in train_palm
    hooks.ThroughputHook(ignored_steps=10, tflop_per_step = tflop),
        TypeError: __init__() got an unexpected keyword argument 'tflop_per_step'
```
I also tried to build colossalai 0.1.5 based on your docker file, I got
```
NameError: name 'colossal_C' is not defined
```

So can you provide some suggestions about how to set up the environment in a correct way?

**Comment by binmakeswell** [comment]
Our web service is down this morning, and it has been fixed, sorry for the inconvenience.

**Comment by player1321** [comment]
Got it, thanks
